/**
 * EyeSeeTea customization - Biometrics Template Storage
 *
 * Replicates the `Biometrics Template` tracked entity attribute (UID fixed in the app,
 * `biometricTemplateAttributeId` in commonskmm `attributes.kt`) from a source DHIS2 server
 * to a target one, and links it wherever the `Biometrics` (GUID) attribute is linked:
 *
 *   - every tracked entity type that has `Biometrics`
 *   - every program that has `Biometrics` (or only the ones given with --programs)
 *
 * The target objects are taken from the TARGET server and only the missing link is added,
 * so no other configuration of the target is overwritten. Link UIDs are reused from the
 * source when the same TET/program exists there and the UID is free on the target;
 * otherwise new UIDs are generated by the target server.
 *
 * Credentials are read from `local.properties` (`simprins<Name>Server|User|Pwd`) and never
 * printed.
 *
 * Usage (from the repository root):
 *
 *   npx tsx eyeseetea-docs/scripts/simprints/replicate-biometrics-template.ts \
 *     --target GhanaPlay [--source Dev] [--mode plan|validate|commit] \
 *     [--programs id1,id2] [--exclude id1,id2] [--out dir] [--properties path]
 *
 * Modes:
 *   plan      only fetches, backs up and writes metadata.json (no POST)
 *   validate  (default) also POSTs to /api/metadata with importMode=VALIDATE
 *   commit    also imports for real (atomicMode=ALL)
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const TEMPLATE_ATTRIBUTE_ID = "BP90qVFNazj";
const BIOMETRICS_ATTRIBUTE_ID = "KdZcTAZfIk4";
const AUDIT_FIELDS = ["created", "lastUpdated", "createdBy", "lastUpdatedBy", "href"];

// ---------------------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------------------

type Mode = "plan" | "validate" | "commit";

interface Options {
    readonly source: string;
    readonly target: string;
    readonly mode: Mode;
    readonly programs?: readonly string[];
    readonly exclude: readonly string[];
    readonly out: string;
    readonly properties: string;
}

interface Server {
    readonly name: string;
    readonly baseUrl: string;
    readonly authorization: string;
}

interface Ref {
    readonly id: string;
}

interface Link {
    readonly id: string;
    readonly trackedEntityAttribute: Ref;
    readonly sortOrder?: number;
    readonly [key: string]: unknown;
}

interface TrackedEntityType {
    readonly id: string;
    readonly name: string;
    readonly trackedEntityTypeAttributes: readonly Link[];
    readonly [key: string]: unknown;
}

interface Program {
    readonly id: string;
    readonly name: string;
    readonly programTrackedEntityAttributes: readonly Link[];
    readonly [key: string]: unknown;
}

type Attribute = Readonly<Record<string, unknown>>;

/** Everything read from both servers; the rest of the script only transforms it. */
interface Context {
    readonly isSuperuser: boolean;
    readonly attributeToCreate?: Attribute;
    readonly targetTets: readonly TrackedEntityType[];
    readonly targetPrograms: readonly Program[];
    readonly sourceTets: ReadonlyMap<string, TrackedEntityType>;
    readonly sourcePrograms: ReadonlyMap<string, Program>;
    readonly programsWithoutBiometrics: readonly string[];
    readonly programsLeftOut: readonly Program[];
}

type Owner = { readonly kind: "tet"; readonly object: TrackedEntityType } | { readonly kind: "program"; readonly object: Program };

/** An object of the target that still needs the template link. */
interface PendingLink {
    readonly owner: Owner;
    readonly sourceUid?: string;
}

interface Assignment {
    readonly uid: string;
    readonly reused: boolean;
}

interface Plan {
    readonly metadata: Readonly<Record<string, readonly unknown[]>>;
    readonly lines: readonly string[];
}

interface ImportReport {
    readonly status: string;
    readonly response?: {
        readonly stats?: Record<string, number>;
        readonly typeReports?: readonly {
            readonly klass: string;
            readonly stats: Record<string, number>;
            readonly objectReports?: readonly {
                readonly uid?: string;
                readonly errorReports?: readonly { readonly errorCode: string; readonly message: string }[];
            }[];
        }[];
    };
}

// ---------------------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------------------

const parseList = (value?: string): string[] | undefined =>
    value
        ?.split(",")
        .map(item => item.trim())
        .filter(Boolean);

const toPairs = (argv: readonly string[]): [string, string][] =>
    argv.length === 0 ? [] : [[argv[0], argv[1]], ...toPairs(argv.slice(2))];

function parseArgs(argv: readonly string[], now: Date): Options {
    const pairs = toPairs(argv);
    const invalid = pairs.find(([key, value]) => !key.startsWith("--") || value === undefined || value.startsWith("--"));
    if (invalid) throw new Error(`Invalid argument: ${invalid[0]} ${invalid[1] ?? ""}`);

    const args = new Map(pairs.map(([key, value]) => [key.slice(2), value] as const));

    const target = args.get("target");
    if (!target) throw new Error("--target is required (e.g. --target GhanaPlay)");

    const mode = args.get("mode") ?? "validate";
    if (!isMode(mode)) throw new Error(`Invalid --mode: ${mode}`);

    const timestamp = now.toISOString().replace(/[:.]/g, "-");

    return {
        source: args.get("source") ?? "Dev",
        target,
        mode,
        programs: parseList(args.get("programs")),
        exclude: parseList(args.get("exclude")) ?? [],
        out: resolve(args.get("out") ?? join("build", "replicate-biometrics-template", `${target}-${timestamp}`)),
        properties: resolve(args.get("properties") ?? "local.properties"),
    };
}

const isMode = (value: string): value is Mode => ["plan", "validate", "commit"].includes(value);

const parseProperties = (content: string): ReadonlyMap<string, string> =>
    new Map(
        content
            .split(/\r?\n/)
            .map(line => line.match(/^\s*([^#=\s]+)\s*=(.*)$/))
            .filter((match): match is RegExpMatchArray => match !== null)
            .map(match => [match[1], match[2].trim()] as const),
    );

function toServer(properties: ReadonlyMap<string, string>, name: string): Server {
    const get = (suffix: string) => {
        const key = `simprins${name}${suffix}`;
        const value = properties.get(key);
        if (!value) throw new Error(`Missing ${key} in local.properties`);
        return value;
    };

    return {
        name,
        baseUrl: get("Server").replace(/\/+$/, ""),
        authorization: "Basic " + Buffer.from(`${get("User")}:${get("Pwd")}`).toString("base64"),
    };
}

const omit = <T extends Readonly<Record<string, unknown>>>(object: T, keys: readonly string[]): T =>
    Object.fromEntries(Object.entries(object).filter(([key]) => !keys.includes(key))) as T;

const linksOf = (owner: Owner): readonly Link[] =>
    owner.kind === "tet" ? owner.object.trackedEntityTypeAttributes : owner.object.programTrackedEntityAttributes;

const hasAttribute = (links: readonly Link[] | undefined, attributeId: string): boolean =>
    (links ?? []).some(link => link.trackedEntityAttribute.id === attributeId);

const templateLinkOf = (links: readonly Link[] | undefined): Link | undefined =>
    links?.find(link => link.trackedEntityAttribute.id === TEMPLATE_ATTRIBUTE_ID);

const nextSortOrder = (links: readonly Link[]): number => Math.max(0, ...links.map(link => link.sortOrder ?? 0)) + 1;

const labelOf = (owner: Owner): string => (owner.kind === "tet" ? "TET    " : "Program");

const ownersOf = (context: Context): Owner[] => [
    ...context.targetTets.map(object => ({ kind: "tet", object }) as const),
    ...context.targetPrograms.map(object => ({ kind: "program", object }) as const),
];

const sourceOwnerOf = (context: Context, owner: Owner): Owner | undefined => {
    if (owner.kind === "tet") {
        const object = context.sourceTets.get(owner.object.id);
        return object && { kind: "tet", object };
    }
    const object = context.sourcePrograms.get(owner.object.id);
    return object && { kind: "program", object };
};

const pendingLinks = (context: Context): PendingLink[] =>
    ownersOf(context)
        .filter(owner => !templateLinkOf(linksOf(owner)))
        .map(owner => {
            const sourceOwner = sourceOwnerOf(context, owner);
            return { owner, sourceUid: sourceOwner && templateLinkOf(linksOf(sourceOwner))?.id };
        });

/**
 * Gives each pending link the source UID when it is free on the target and not already
 * taken by an earlier link, or the next generated UID otherwise.
 */
function assignUids(
    pending: readonly PendingLink[],
    freeSourceUids: ReadonlySet<string>,
    generated: readonly string[],
): Assignment[] {
    const initial = { assignments: [] as Assignment[], taken: new Set<string>(), generated };

    return pending.reduce((state, { sourceUid }) => {
        const reuse = sourceUid !== undefined && freeSourceUids.has(sourceUid) && !state.taken.has(sourceUid);
        const assignment = reuse ? { uid: sourceUid, reused: true } : { uid: state.generated[0], reused: false };

        return {
            assignments: [...state.assignments, assignment],
            taken: new Set([...state.taken, assignment.uid]),
            generated: reuse ? state.generated : state.generated.slice(1),
        };
    }, initial).assignments;
}

const newTetLink = (tet: TrackedEntityType, uid: string): Link => ({
    id: uid,
    trackedEntityType: { id: tet.id },
    trackedEntityAttribute: { id: TEMPLATE_ATTRIBUTE_ID },
    displayInList: false,
    mandatory: false,
    searchable: false,
});

const newProgramLink = (program: Program, uid: string): Link => ({
    id: uid,
    program: { id: program.id },
    trackedEntityAttribute: { id: TEMPLATE_ATTRIBUTE_ID },
    sortOrder: nextSortOrder(program.programTrackedEntityAttributes),
    displayInList: false,
    mandatory: false,
    searchable: false,
    allowFutureDate: false,
    renderOptionsAsRadio: false,
});

const withLink = (owner: Owner, uid: string): Owner =>
    owner.kind === "tet"
        ? {
              kind: "tet",
              object: {
                  ...owner.object,
                  trackedEntityTypeAttributes: [...owner.object.trackedEntityTypeAttributes, newTetLink(owner.object, uid)],
              },
          }
        : {
              kind: "program",
              object: {
                  ...owner.object,
                  programTrackedEntityAttributes: [
                      ...owner.object.programTrackedEntityAttributes,
                      newProgramLink(owner.object, uid),
                  ],
              },
          };

function describeLink(owner: Owner, { uid, reused }: Assignment): string {
    const label = labelOf(owner);
    const origin = reused ? "reused from source" : "new";
    const sortOrder =
        owner.kind === "program" ? `, sortOrder ${nextSortOrder(owner.object.programTrackedEntityAttributes)}` : "";
    return `${label}  ${owner.object.id} ${owner.object.name}: add link ${uid} (${origin})${sortOrder}`;
}

const describeSkipped = (context: Context): string[] =>
    ownersOf(context)
        .filter(owner => templateLinkOf(linksOf(owner)))
        .map(owner => `${labelOf(owner)}  ${owner.object.id} ${owner.object.name}: already linked, skipped`);

function buildPlan(context: Context, pending: readonly PendingLink[], assignments: readonly Assignment[]): Plan {
    const updated = pending.map((item, index) => withLink(item.owner, assignments[index].uid));
    const objectsOf = <K extends Owner["kind"]>(kind: K) =>
        updated.filter(owner => owner.kind === kind).map(owner => owner.object);

    const metadata = Object.fromEntries(
        [
            ["trackedEntityAttributes", context.attributeToCreate ? [context.attributeToCreate] : []],
            ["trackedEntityTypes", objectsOf("tet")],
            ["programs", objectsOf("program")],
        ].filter(([, objects]) => (objects as unknown[]).length > 0),
    );

    const lines = [
        `Attribute ${TEMPLATE_ATTRIBUTE_ID}: ${context.attributeToCreate ? "create (copied from source)" : "already exists, skipped"}`,
        ...pending.map((item, index) => describeLink(item.owner, assignments[index])),
        ...describeSkipped(context),
    ];

    return { metadata, lines };
}

const reportErrors = (report: ImportReport): string[] =>
    (report.response?.typeReports ?? []).flatMap(typeReport =>
        (typeReport.objectReports ?? []).flatMap(objectReport =>
            (objectReport.errorReports ?? []).map(
                error => `ERROR ${objectReport.uid ?? ""} ${error.errorCode}: ${error.message}`,
            ),
        ),
    );

// ---------------------------------------------------------------------------------------
// DHIS2 API (IO)
// ---------------------------------------------------------------------------------------

async function request<T>(server: Server, path: string, body?: unknown): Promise<T> {
    const method = body === undefined ? "GET" : "POST";
    const response = await fetch(`${server.baseUrl}/api/${path}`, {
        method,
        headers: {
            Authorization: server.authorization,
            Accept: "application/json",
            ...(body !== undefined ? { "Content-Type": "application/json" } : {}),
        },
        body: body !== undefined ? JSON.stringify(body) : undefined,
    });

    const text = await response.text();
    const json = (() => {
        try {
            return JSON.parse(text) as T & { message?: string };
        } catch {
            throw new Error(`[${server.name}] ${method} ${path}: HTTP ${response.status}, non-JSON response`);
        }
    })();

    // Metadata import returns 409 with a JSON report on validation errors: let the caller print it.
    const isImportReport = path.startsWith("metadata") && response.status === 409;
    if (!response.ok && !isImportReport) {
        throw new Error(`[${server.name}] ${method} ${path}: HTTP ${response.status} ${json.message ?? ""}`);
    }
    return json;
}

async function exists(server: Server, uid: string): Promise<boolean> {
    const response = await fetch(`${server.baseUrl}/api/identifiableObjects/${uid}`, {
        headers: { Authorization: server.authorization, Accept: "application/json" },
    });
    if (response.status === 404) return false;
    if (response.ok) return true;
    throw new Error(`[${server.name}] identifiableObjects/${uid}: HTTP ${response.status}`);
}

const getOwner = <T>(server: Server, resource: string, uid: string): Promise<T> =>
    request<T>(server, `${resource}/${uid}?fields=:owner`);

async function getOwnersIfExist<T extends { id: string }>(
    server: Server,
    resource: string,
    uids: readonly string[],
): Promise<ReadonlyMap<string, T>> {
    const found = await Promise.all(
        uids.map(async (uid): Promise<T | undefined> =>
            (await exists(server, uid)) ? getOwner<T>(server, resource, uid) : undefined,
        ),
    );
    return new Map(found.flatMap((object): [string, T][] => (object ? [[object.id, object]] : [])));
}

async function fetchContext(options: Options, source: Server, target: Server): Promise<Context> {
    const [me, sourceAttribute, targetHasAttribute, tetList, programList] = await Promise.all([
        request<{ authorities: string[] }>(target, "me?fields=authorities"),
        getOwner<Attribute>(source, "trackedEntityAttributes", TEMPLATE_ATTRIBUTE_ID),
        exists(target, TEMPLATE_ATTRIBUTE_ID),
        request<{ trackedEntityTypes: TrackedEntityType[] }>(
            target,
            "trackedEntityTypes?paging=false&fields=id,name,trackedEntityTypeAttributes[id,trackedEntityAttribute[id]]",
        ),
        request<{ programs: Program[] }>(
            target,
            "programs?paging=false&fields=id,name,programTrackedEntityAttributes[id,trackedEntityAttribute[id]]",
        ),
    ]);

    const tetIds = tetList.trackedEntityTypes
        .filter(tet => hasAttribute(tet.trackedEntityTypeAttributes, BIOMETRICS_ATTRIBUTE_ID))
        .map(tet => tet.id);
    const programsWithBiometrics = programList.programs
        .filter(program => hasAttribute(program.programTrackedEntityAttributes, BIOMETRICS_ATTRIBUTE_ID))
        .map(program => program.id);
    const programIds = (options.programs ?? programsWithBiometrics).filter(id => !options.exclude.includes(id));

    const [targetTets, targetPrograms, sourceTets, sourcePrograms, attributeToCreate] = await Promise.all([
        Promise.all(tetIds.map(id => getOwner<TrackedEntityType>(target, "trackedEntityTypes", id))),
        Promise.all(programIds.map(id => getOwner<Program>(target, "programs", id))),
        getOwnersIfExist<TrackedEntityType>(source, "trackedEntityTypes", tetIds),
        getOwnersIfExist<Program>(source, "programs", programIds),
        targetHasAttribute ? Promise.resolve(undefined) : attributeForTarget(sourceAttribute, target),
    ]);

    return {
        isSuperuser: me.authorities.includes("ALL"),
        attributeToCreate,
        targetTets,
        targetPrograms,
        sourceTets,
        sourcePrograms,
        programsWithoutBiometrics: programIds.filter(id => !programsWithBiometrics.includes(id)),
        programsLeftOut: programList.programs.filter(program => !programIds.includes(program.id)),
    };
}

/** Source attribute without audit fields, and without a sharing owner the target does not know. */
async function attributeForTarget(sourceAttribute: Attribute, target: Server): Promise<Attribute> {
    const attribute = omit(sourceAttribute, AUDIT_FIELDS);
    const sharing = attribute.sharing as Readonly<Record<string, unknown>> | undefined;
    const owner = sharing?.owner as string | undefined;

    return owner && !(await exists(target, owner))
        ? { ...attribute, sharing: omit(sharing ?? {}, ["owner"]) }
        : attribute;
}

async function resolveAssignments(target: Server, pending: readonly PendingLink[]): Promise<Assignment[]> {
    const sourceUids = [...new Set(pending.flatMap(item => (item.sourceUid ? [item.sourceUid] : [])))];
    const free = await Promise.all(sourceUids.map(async uid => [uid, !(await exists(target, uid))] as const));
    const freeSourceUids = new Set(free.filter(([, isFree]) => isFree).map(([uid]) => uid));

    const needed = pending.length - freeSourceUids.size;
    const generated =
        needed > 0 ? (await request<{ codes: string[] }>(target, `system/id?limit=${needed}`)).codes : [];

    return assignUids(pending, freeSourceUids, generated);
}

// ---------------------------------------------------------------------------------------
// Output (IO)
// ---------------------------------------------------------------------------------------

const writeJson = (path: string, value: unknown) => writeFileSync(path, JSON.stringify(value, null, 2));

function writeBackup(dir: string, context: Context) {
    mkdirSync(dir, { recursive: true });
    context.targetTets.forEach(tet => writeJson(join(dir, `trackedEntityType_${tet.id}.json`), tet));
    context.targetPrograms.forEach(program => writeJson(join(dir, `program_${program.id}.json`), program));
}

function printContextWarnings(context: Context, target: Server) {
    if (!context.isSuperuser) {
        console.warn(
            `WARNING: the ${target.name} user is not a superuser (no "ALL" authority). ` +
                "It may not see every program and may not be allowed to import metadata.",
        );
    }
    if (context.programsWithoutBiometrics.length > 0) {
        console.warn(`WARNING: programs without the Biometrics attribute: ${context.programsWithoutBiometrics.join(", ")}`);
    }
}

function printPlan(plan: Plan, context: Context) {
    console.log(["", "Plan:", ...plan.lines.map(line => `  ${line}`)].join("\n"));

    if (context.programsLeftOut.length > 0) {
        console.log(
            [
                "",
                "Programs visible on the target that will NOT get the attribute:",
                ...context.programsLeftOut.map(program => `  ${program.id} ${program.name}`),
            ].join("\n"),
        );
    }
}

function printReport(importMode: string, report: ImportReport) {
    const typeLines = (report.response?.typeReports ?? []).map(
        typeReport => `  ${typeReport.klass.split(".").pop()}: ${JSON.stringify(typeReport.stats)}`,
    );
    console.log(
        [
            "",
            `${importMode}: ${report.status}`,
            `  stats: ${JSON.stringify(report.response?.stats ?? {})}`,
            ...typeLines,
            ...reportErrors(report).map(error => `    ${error}`),
        ].join("\n"),
    );
}

// ---------------------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------------------

async function main() {
    const options = parseArgs(process.argv.slice(2), new Date());
    if (!existsSync(options.properties)) throw new Error(`Properties file not found: ${options.properties}`);

    const properties = parseProperties(readFileSync(options.properties, "utf8"));
    const source = toServer(properties, options.source);
    const target = toServer(properties, options.target);

    console.log(`Source: ${source.name} | Target: ${target.name} | Mode: ${options.mode}`);

    const context = await fetchContext(options, source, target);
    printContextWarnings(context, target);

    const pending = pendingLinks(context);
    const plan = buildPlan(context, pending, await resolveAssignments(target, pending));
    printPlan(plan, context);

    const backupDir = join(options.out, "backup");
    const metadataPath = join(options.out, "metadata.json");
    writeBackup(backupDir, context);
    writeJson(metadataPath, plan.metadata);
    console.log(`\nBackup:   ${backupDir}\nMetadata: ${metadataPath}`);

    if (Object.keys(plan.metadata).length === 0) {
        console.log("\nNothing to do: the target is already up to date.");
        return;
    }
    if (options.mode === "plan") return;

    const importMode = options.mode === "commit" ? "COMMIT" : "VALIDATE";
    const report = await request<ImportReport>(
        target,
        `metadata?importMode=${importMode}&importStrategy=CREATE_AND_UPDATE&atomicMode=ALL&importReportMode=ERRORS`,
        plan.metadata,
    );
    writeJson(join(options.out, `import-report-${importMode.toLowerCase()}.json`), report);
    printReport(importMode, report);

    if (report.status !== "OK" || reportErrors(report).length > 0) process.exitCode = 1;
}

main().catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
});
